"use client";

import Head from "next/head";
import NavBarGeneral from "@/app/components/NavBarGeneral";
import ExperienceSection from "@/app/components/ExperienceSection";

export default function Experience() {
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b px-10 from-gray-900 to-violet-950 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <NavBarGeneral />
          <ExperienceSection />
        </section>
      </main>
    </div>
    );
}