"use client";

import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill, BsGithub, BsInstagram, BsLinkedin } from "react-icons/bs";
import NavBarGeneral from "@/app/components/NavBarGeneral";

export default function About() {
    const [darkMode, setDarkMode] = useState(true);

    return (
        <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-white to-violet-700 px-10 dark:bg-gradient-to-b dark:from-gray-900 dark:to-violet-950 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <NavBarGeneral />
        </section>
      </main>
    </div>
    );
}