"use client";

import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill, BsGithub, BsInstagram, BsLinkedin } from "react-icons/bs";
import NavBarGeneral from "@/app/components/NavBarGeneral";

export default function About() {
    const [darkMode, setDarkMode] = useState(true);

    return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-white to-violet-700 px-10 dark:bg-gradient-to-b dark:from-gray-900 dark:to-violet-950 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <NavBarGeneral />
          <div className="flex flex-col text-center">
            <div className="mt-52 mx-96">
              <h1 className="text-3xl md:text-6xl font-bold border-b-2 py-5 bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text">
                About Me
              </h1>
              <p className="text-xl text-left mt-5">
                Hello and welcome to my website! My name is Michael Tripp; I am a Data & Systems Analyst by day and a Software Developer by night (or early morning).
                I love to learn and am passionate about having a growth mindset. My goal is to not only use this website to showcase some of my projects and skills
                as a developer, but also provide myself with a platform for continual learning and development.
                A little bit about me: I 
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
    );
}