import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { BsLinkedin, BsGithub, BsDiscord, BsInstagram } from 'react-icons/bs'
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Michael Tripp Portfolio</title>
        <meta name="description" content="Generated by creator" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen"> 
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl text-black font-burtons'>developedbyed</h1>
            <ul className="flex items-center">
              <l1>
                <BsFillMoonStarsFill className="cursor-pointer text-black text-2xl" />
              </l1>
              <li>
                <a className="bg-gradient-to-br from-cyan-400 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Michael Tripp</h2>
            <h3 className='text-2xl py-2 text-black'>Developer and designer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Freelancer providing services for programming and design content needs. Join me down below and lets get cracking!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <BsLinkedin />
            <BsGithub />
            <BsInstagram />
            <BsDiscord />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div >
            <h3 className='text-black text-3xl py-1'>Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='mx-auto' src={design} width={100} height={100} />
              <h3 className='text-black text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='text-black py-2'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='mx-auto' src={code} width={100} height={100} />
              <h3 className='text-black text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='text-black py-2'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='mx-auto' src={consulting} width={100} height={100} />
              <h3 className='text-black text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='text-black py-2'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-black text-3xl py-1'>Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

        {/* Continue here! */}
        </section>

      </main>
    </div>
  )
}
