import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { BsLinkedin, BsGithub, BsDiscord, BsInstagram } from 'react-icons/bs'
import { AiFillGithub } from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Michael Tripp Portfolio</title>
        <meta name="description" content="Generated by creator" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen"> 
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl text-black font-burtons'>developedbyed</h1>
            <ul className="flex items-center">
              <l1>
                <BsFillMoonStarsFill className="cursor-pointer text-black text-2xl" />
              </l1>
              <li>
                <a className="bg-gradient-to-br from-cyan-400 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div>
            <h2>Michael Tripp</h2>
            <h3>Developer and designer.</h3>
            <p>
              Freelancer providing services for programming and design content needs. Join me down below and lets get cracking!
            </p>
          </div>
          <div>
            <BsLinkedin className='text-black'/>
            <BsGithub className='text-black'/>
            <BsInstagram className='text-black'/>
            <BsDiscord className='text-black'/>
          </div>
        </section>
      </main>
    </div>
  )
}
