"use client";

import Head from "next/head";
import { useState } from "react";
import { BsGithub, BsInstagram, BsLinkedin } from "react-icons/bs";

import NavBarHome from "../../components/NavBarHome";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-white to-violet-700 px-10 dark:bg-gradient-to-b dark:from-gray-900 dark:to-violet-950 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <NavBarHome />
          <div className="flex h-screen flex-col text-center">
            <div className="m-auto">
              <h3 className="font-mono text-2xl pb-5 pt-28 bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text md:text-3xl">
                Hi, my name is
              </h3>
              <h2 className="text-5xl text-black dark:text-white font-bold md:text-9xl transition-transform duration-300 hover:scale-105">
                Michael Tripp<span className="text-5xl bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text md:text-7xl">.</span>
              </h2>
              <h3 className="font-mono text-2xl pt-5 bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text md:text-3xl">
                Nice to meet you!
              </h3>
              <div className="text-5xl flex justify-center gap-16 pt-10 text-gray-600 dark:text-gray-400">
                <a className="transition-all duration-300 hover:scale-110 hover:text-gray-300" href="https://www.linkedin.com/in/michaelctripp/" target="_blank"><BsLinkedin /></a>
                <a className="transition-all duration-300 hover:scale-110 hover:text-gray-300" href="https://github.com/Mctripp10" target="_blank"><BsGithub /></a>
                <a className="transition-all duration-300 hover:scale-110 hover:text-gray-300" href="https://www.instagram.com/mc_tripp/" target="_blank"><BsInstagram /></a>
              </div>
          </div>
            </div>
        </section>

      {/*
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Background</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gradient-to-b dark:from-pink-500 dark:to-violet-600 flex-1">
              <Image className="mx-auto" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-800 dark:text-white">
                Beautiful Designs
              </h3>
              <p className="py-2 text-gray-800 dark:text-white">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-300">Design Tools I Use</h4>
              <p className="text-gray-800 dark:text-white py-1">Photoshop</p>
              <p className="text-gray-800 dark:text-white py-1">Illustrator</p>
              <p className="text-gray-800 dark:text-white py-1">Figma</p>
              <p className="text-gray-800 dark:text-white py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b dark:from-pink-500 dark:to-violet-600 flex-1">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-800 dark:text-white">
                Code your dream project
              </h3>
              <p className="py-2 text-gray-800 dark:text-white">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-300">Design Tools I Use</h4>
              <p className="text-gray-800 dark:text-white py-1">Photoshop</p>
              <p className="text-gray-800 dark:text-white py-1">Illustrator</p>
              <p className="text-gray-800 dark:text-white py-1">Figma</p>
              <p className="text-gray-800 dark:text-white py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b dark:from-pink-500 dark:to-violet-600 flex-1">
              <Image className="mx-auto" src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-800 dark:text-white">Consulting</h3>
              <p className="py-2 text-gray-800 dark:text-white">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-300">Design Tools I Use</h4>
              <p className="text-gray-800 dark:text-white py-1">Illustrator</p>
              <p className="text-gray-800 dark:text-white py-1">Figma</p>
              <p className="text-gray-800 dark:text-white py-1">Indesign</p>
              <p className="text-gray-800 dark:text-white py-1">Photoshop</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
  */}
      </main>
    </div>
  );
}