"use client";

import {useRef} from 'react';
import Head from "next/head";
<<<<<<< Updated upstream:app/pages/home/page.js
import { BsGithub, BsInstagram, BsLinkedin } from "react-icons/bs";

import NavBarHome from "../../components/NavBarHome";

export default function Home() {
=======
import Home from "@/components/Home";
import About from "@/components/About";
import Projects from "@/components/Projects";
import Experience from "@/components/Experience";
import Contact from "@/components/Contact";
>>>>>>> Stashed changes:app/page.js

export default function App() {
  const homeRef = useRef(null);
  const aboutRef = useRef(null);
  const projectsRef = useRef(null);
  const experienceRef = useRef(null);
  const contactRef = useRef(null);
  const handleClickHome = () => {
    homeRef.current?.scrollIntoView({behavior: 'smooth'});
  };
  const handleClickAbout = () => {
    aboutRef.current?.scrollIntoView({behavior: 'smooth'});
  };
  const handleClickProjects = () => {
    projectsRef.current?.scrollIntoView({behavior: 'smooth'});
  };
  const handleClickExperience = () => {
    experienceRef.current?.scrollIntoView({behavior: 'smooth'});
  };
  const handleClickContact = () => {
    contactRef.current?.scrollIntoView({behavior: 'smooth'});
  }
  return (
    <div>
      <Head>
<<<<<<< Updated upstream:app/pages/home/page.js
        <title>Create Next App</title>
=======
        <title>Michael Tripp</title>
>>>>>>> Stashed changes:app/page.js
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< Updated upstream:app/pages/home/page.js
      <main className="px-10 bg-gradient-to-b from-gray-900 to-violet-950 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <NavBarHome />
          <div className="flex h-screen flex-col text-center">
            <div className="m-auto">
              <h3 className="font-mono text-2xl pb-5 pt-28 bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text md:text-3xl">
                Hi, my name is
              </h3>
              <h2 className="text-5xl text-white font-bold md:text-7xl lg:text-8xl xl:text-9xl transition-transform duration-300 hover:scale-105">
                Michael Tripp<span className="text-5xl bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text md:text-7xl">.</span>
              </h2>
              <h3 className="font-mono text-2xl pt-5 bg-gradient-to-br from-pink-500 to-violet-600 text-transparent bg-clip-text md:text-3xl">
                Nice to meet you!
              </h3>
              <div className="text-5xl flex justify-center gap-16 pt-10 text-gray-400">
                <a className="transition-all duration-300 hover:scale-110 hover:text-gray-300" href="https://www.linkedin.com/in/michaelctripp/" target="_blank"><BsLinkedin /></a>
                <a className="transition-all duration-300 hover:scale-110 hover:text-gray-300" href="https://github.com/Mctripp10" target="_blank"><BsGithub /></a>
                <a className="transition-all duration-300 hover:scale-110 hover:text-gray-300" href="https://www.instagram.com/mc_tripp/" target="_blank"><BsInstagram /></a>
              </div>
          </div>
            </div>
        </section>
=======
      <main className="bg-slate-900">
      <div>
            <nav className="w-full fixed right-0 z-20 backdrop-filter backdrop-blur-lg shadow-2xl">
                <div className="flex items-center justify-center mx-auto">
                    <div className="my-2.5 sm:my-10">
                        <div>
                            <ul className="flex flex-col sm:flex-row font-mono gap-1 sm:gap-10 text-xl text-white items-center justify-center xl:gap-16">
                                <li className="text-center hover:text-sky-500 transition-all duration-200">
                                    <button onClick={handleClickHome}>
                                        Home
                                    </button>
                                </li>
                                <li className="text-center hover:text-sky-500 transition-all duration-200">
                                    <button onClick={handleClickAbout}>
                                        About
                                    </button>
                                </li>
                                <li className="text-center hover:text-sky-500 transition-all duration-200">
                                    <button onClick={handleClickProjects}>
                                        Projects
                                    </button>
                                </li>
                                <li className="text-center hover:text-sky-500 transition-all duration-200">
                                    <button onClick={handleClickExperience}>
                                        Experience
                                    </button>
                                </li>
                                <li className="text-center hover:text-sky-500 transition-all duration-200">
                                    <button onClick={handleClickContact}>
                                        Contact
                                    </button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div ref={homeRef}>
          <Home />
        </div>
        <div ref={aboutRef}>
          <About />
        </div>
        <div ref={projectsRef}>
          <Projects />
        </div>
        <div ref={experienceRef}>
          <Experience />
        </div>
>>>>>>> Stashed changes:app/page.js
      </main>
      <div ref={contactRef}>
          <Contact />
        </div>
    </div>
  );
}